# Generated by Django 4.0.6 on 2022-12-01 09:34

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_address', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_type', models.CharField(choices=[('NONE', 'NONE'), ('ERC20', 'ERC20'), ('ERC721', 'ERC721')], default='NONE', max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('stark_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractTxns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('assest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('record_type', models.IntegerField(choices=[('0', 'DEFAULT'), ('1', 'DepositRecordType'), ('2', 'MintRecordType'), ('3', 'TransferFromRecordType'), ('4', 'WithdrawRecordType'), ('7', 'ASKOrderRecordType'), ('8', 'BIDOrderRecordType')], default='0')),
                ('display_value', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('record_status', models.IntegerField(choices=[('0', 'DEFAULT'), ('1', 'Submitted'), ('2', 'Accepted'), ('3', 'Failed'), ('4', 'Proved'), ('5', 'ProvedError')], default='0')),
                ('base_asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('base_asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('base_contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('fee_asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fee_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('fee_token_asset', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_asset_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('token_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddio.contract')),
                ('fromAddr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromAddress', to='reddio.user')),
                ('toAddr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toAddress', to='reddio.user')),
            ],
        ),
    ]
